apiVersion: v1
kind: Service
metadata:
  name: hbase-master-1
  namespace: hadoop     # 设置命名空间
spec:
  selector:
    app: hbase-master-pod-1    # 绑定pod
  ports:
    - name: rpc
      port: 60000
      targetPort: 60000        # 配置的hbase的链接端口
    - name: info
      port: 60001            # hbase运行状态的网页查询端口
      targetPort: 60001
    - name: thrift
      port: 9090           #　thrift服务器ip，让外界通过thrift来访问hbase
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-region-1
  namespace: hadoop     # 设置命名空间
spec:
  selector:
    app: hbase-region-pod-1    # 绑定pod
  ports:
    - name: rpc
      port: 60000
      targetPort: 60000        # 配置的hbase的链接端口   
    - name: info
      port: 60001            # hbase运行状态的网页查询端口
      targetPort: 60001
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-region-2
  namespace: hadoop     # 设置命名空间
spec:
  selector:
    app: hbase-region-pod-2    # 绑定pod
  ports:
    - name: rpc
      port: 60000
      targetPort: 60000        # 配置的hbase的链接端口   
    - name: info
      port: 60001            # hbase运行状态的网页查询端口
      targetPort: 60001

