apiVersion: v1
kind: Namespace
metadata:
  name: cloudai-2
  labels:  
    name: cloudai-2
---

apiVersion: v1
kind: Secret
metadata:
  namespace: cloudai-2
  name: hub.cloudx5.com
  annotations:
    kubernetes.io/service-account.name: default
data:
  .dockercfg: eyJodWIuY2xvdWR4NS5jb20iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiMSIsImVtYWlsIjoidGlnZXI0MzVAcXEuY29tIiwiYXV0aCI6IllXUnRhVzQ2TVE9PSJ9fQ==
type: kubernetes.io/dockercfg
