
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
  namespace: hadoop     # 设置命名空间
  labels:
      name: zookeeper-1
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: followers
      port: 2888
      targetPort: 2888
    - name: election
      port: 3888
      targetPort: 3888
  selector:
    name: zookeeper
    server-id: "1"
  type: ClusterIP          # 只能集群内部访问
---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-2
  namespace: hadoop     # 设置命名空间
  labels:
      name: zookeeper-2
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: followers
      port: 2888
      targetPort: 2888
    - name: election
      port: 3888
      targetPort: 3888
  selector:
    name: zookeeper
    server-id: "2"
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3
  namespace: hadoop     # 设置命名空间
  labels:
      name: zookeeper-3
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: followers
      port: 2888
      targetPort: 2888
    - name: election
      port: 3888
      targetPort: 3888
  selector:
    name: zookeeper
    server-id: "3"
  type: ClusterIP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-1
  namespace: hadoop     # 设置命名空间
spec:
  selector:    
    matchLabels:
      name: zookeeper   # 根据标签选择选择部署下一层的容器组，复制保持容器组的正常运行个数
      server-id: "1"
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
        server-id: "1"
    spec:
      volumes:
        - hostPath:
            path: /hbase/zookeeper1/data
          name: data
        - hostPath:
            path: /hbase/zookeeper1/conf
          name: conf
        - hostPath:
            path: /hbase/zookeeper1/log
          name: log
      imagePullSecrets:
      - name: hub.cloudx5.com
      nodeName: k8s-node1
      initContainers:
      - name: dependency-checker
        image: hub.cloudx5.com/justep/busybox:1.30
        command: ["sh", "-c", "until nslookup hdfs-namenode-service; do echo waiting for hdfs-namenode-service; sleep 2; done;"]
      containers:
        - name: server
          image: hub.cloudx5.com/justep/hbase-zookeeper:1.0.0
          imagePullPolicy: Always
          livenessProbe: 
              exec: 
                  command: ["kinit", "-R"]
              initialDelaySeconds: 300 
              timeoutSeconds: 5 
              periodSeconds: 1800 
          env:
            - name: SERVER_ID
              value: "1"
            - name: MAX_SERVERS
              value: "3"
            - name: SERVER_PRINCIPAL 
              value: "zookeeper/zookeeper-1.hadoop.svc.cluster.local@JUSTEP.COM"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: /opt/zookeeper/data
              name: data
            - mountPath: /opt/zookeeper/fromhost
              name: conf
            - mountPath: /opt/zookeeper/log
              name: log
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-2
  namespace: hadoop     # 设置命名空间
spec:
  selector:    
    matchLabels:
      name: zookeeper   # 根据标签选择选择部署下一层的容器组，复制保持容器组的正常运行个数
      server-id: "2"
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
        server-id: "2"
    spec:
      volumes:
        - hostPath:
            path: /hbase/zookeeper2/data
          name: data
        - hostPath:
            path: /hbase/zookeeper2/conf
          name: conf
        - hostPath:
            path: /hbase/zookeeper2/log
          name: log
      imagePullSecrets:
      - name: hub.cloudx5.com
      nodeName: k8s-node2
      initContainers:
      - name: dependency-checker
        image: hub.cloudx5.com/justep/busybox:1.30
        command: ["sh", "-c", "until nslookup hdfs-namenode-service; do echo waiting for hdfs-namenode-service; sleep 2; done;"]
      containers:
        - name: server
          image: hub.cloudx5.com/justep/hbase-zookeeper:1.0.0
          imagePullPolicy: Always
          livenessProbe: 
              exec: 
                  command: ["kinit", "-R"]
              initialDelaySeconds: 300 
              timeoutSeconds: 5 
              periodSeconds: 1800 
          env:
            - name: SERVER_ID
              value: "2"
            - name: MAX_SERVERS
              value: "3"
            - name: SERVER_PRINCIPAL 
              value: "zookeeper/zookeeper-2.hadoop.svc.cluster.local@JUSTEP.COM"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: /opt/zookeeper/data
              name: data
            - mountPath: /opt/zookeeper/fromhost
              name: conf
            - mountPath: /opt/zookeeper/log
              name: log
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-3
  namespace: hadoop     # 设置命名空间
spec:
  selector:    
    matchLabels:
      name: zookeeper   # 根据标签选择选择部署下一层的容器组，复制保持容器组的正常运行个数
      server-id: "3"
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
        server-id: "3"
    spec:
      volumes:
        - hostPath:
            path: /hbase/zookeeper3/data
          name: data
        - hostPath:
            path: /hbase/zookeeper3/conf
          name: conf
        - hostPath:
            path: /hbase/zookeeper3/log
          name: log
      imagePullSecrets:
      - name: hub.cloudx5.com
      nodeName: k8s-monitor
      initContainers:
      - name: dependency-checker
        image: hub.cloudx5.com/justep/busybox:1.30
        command: ["sh", "-c", "until nslookup hdfs-namenode-service; do echo waiting for hdfs-namenode-service; sleep 2; done;"]
      containers:
        - name: server
          image: hub.cloudx5.com/justep/hbase-zookeeper:1.0.0
          imagePullPolicy: Always
          livenessProbe: 
              exec: 
                  command: ["kinit", "-R"]
              initialDelaySeconds: 300 
              timeoutSeconds: 5 
              periodSeconds: 1800 
          env:
            - name: SERVER_ID
              value: "3"
            - name: MAX_SERVERS
              value: "3"
            - name: SERVER_PRINCIPAL 
              value: "zookeeper/zookeeper-3.hadoop.svc.cluster.local@JUSTEP.COM"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - mountPath: /opt/zookeeper/data
              name: data
            - mountPath: /opt/zookeeper/fromhost
              name: conf
            - mountPath: /opt/zookeeper/log
              name: log
