# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: yarn-rm
  namespace: cloudai-2
  labels:
    component: yarn-rm
spec:
  ports:
  - port: 8088
    name: web
  # *.yarn-rm.yarn-cluster.svc.cluster.local
  clusterIP: None
  selector:
    component: yarn-rm
---
# Service to access the yarn web ui
apiVersion: v1
kind: Service
metadata:
  name: yarn-ui
  namespace: cloudai-2
  labels:
    component: yarn-ui
spec:
  ports:
  - port: 8088
    name: web
  selector:
    component: yarn-rm
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: yarn-rm
  namespace: cloudai-2
spec:
  serviceName: "yarn-rm"
  replicas: 1
  template:
    metadata:
      labels:
        component: yarn-rm
    spec:
      terminationGracePeriodSeconds: 0
      imagePullSecrets:
      - name: hub.cloudx5.com   # 镜像拉取秘钥
      containers:
      - name: yarn-rm
        image: hub.cloudx5.com/justep/yarn-rm:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
          name: web
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        env:
          - name: JOBHISTORY_ADDRESS
            value: yarn-rm-0.yarn-rm.yarn-cluster.svc.cluster.local:10020
          - name: JOBHISTORY_WEBAPP_ADDRESS
            value: yarn-rm-0.yarn-rm.yarn-cluster.svc.cluster.local:19888
          - name: HDFSNAMENODERPC_SERVICE_HOST
            value: "10.96.0.5"     # 设置namenode的ip
          - name: HDFSNAMENODERPC_SERVICE_PORT
            value: "4231"           # 设置namenode的端口号

