apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-client
  namespace: cloudai-2
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hadoop-client
  template:
    metadata:
      labels:
        app: hadoop-client
    spec:
      imagePullSecrets:       # 远程拉取镜像，需要拉取秘钥。要先在你的k8s上创建秘钥
      - name: hub.cloudx5.com
      nodeName: k8s-node2     # 根据node的名称选择主机。
      containers:
        - name: hadoop-client
          image: hub.cloudx5.com/justep/hadoop-client:1.0.0
          imagePullPolicy: Always
          livenessProbe: 
              exec: 
                  command: ["kinit", "-R"]
              initialDelaySeconds: 300 
              timeoutSeconds: 5 
              periodSeconds: 1800 
          ports:
            - containerPort: 10000
          resources:
            requests:
              memory: "1024Mi"
              cpu: "100m"
            limits:
              memory: "2048Mi"
              cpu: "4000m"
          env:
            - name: LDAP_HOST
              value: 10.96.100.1:389
            - name: JOBHISTORY_ADDRESS
              value: yarn-rm-0.yarn-rm.yarn-cluster.svc.cluster.local:10020
            - name: JOBHISTORY_WEBAPP_ADDRESS
              value: yarn-rm-0.yarn-rm.yarn-cluster.svc.cluster.local:19888
            - name: HDFSNAMENODERPC_SERVICE_HOST
              value: "10.96.100.5"
            - name: HDFSNAMENODERPC_SERVICE_PORT
              value: "8020"
            - name: HBASE_MASTER_PORT
              value: "60000"
            - name: HBASE_MASTER_INFO_PORT
              value: "60001"
            - name: HBASE_REGION_PORT
              value: "60010"
            - name: HBASE_REGION_INFO_PORT
              value: "60011"
            - name: HDFS_SERVICE
              value: "10.96.100.5"
            - name: HDFS_PORT
              value: "8020"
            - name: ZOOKEEPER_SERVICE_LIST
              value: "10.96.100.11,10.96.100.12,10.96.100.13"
            - name: ZOOKEEPER_PORT
              value: "2181"
            - name: ZNODE_PARENT
              value: hbase
            - name: MY_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: hadoop-client
                  resource: limits.cpu
                  divisor: 1
            - name: MY_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: hadoop-client
                  resource: limits.memory
                  divisor: 1M
          volumeMounts:
            - name: fromhost
              mountPath: /usr/local/fromhost
      volumes:
        - hostPath:
            path: /hadoop-client/fromhost
          name: fromhost

---

#kind: Service
#apiVersion: v1
#metadata:
#  labels:
#    app: hadoop-client
#  name: hadoop-client-service
#  namespace: cloudai-2
#spec:
#  ports:
#    - port: 10000
#      targetPort: 10000
#      name: thrift
#    - port: 10002
#      targetPort: 10002
#      name: webui
#    - port: 9083
#      targetPort: 9083
#      name: metastore
#  selector:
#    app: hadoop-client
#  type: NodePort
#
