kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
  namespace: cloudai-2
spec:
  replicas: 2
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: hub.cloudx5.com/justep/spark:1.0.0
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m

