kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
  namespace: hadoop
spec:
  replicas: 2
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      imagePullSecrets:
      - name: hub.cloudx5.com   # 镜像拉取秘钥
      containers:
        - name: spark-worker
          image: hub.cloudx5.com/justep/spark:1.0.0
          imagePullPolicy: Always
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m

