apiVersion: v1
kind: ReplicationController
metadata:
  name: apache-storm-supervisor
  namespace: cloudai-2
spec:
  replicas: 1
  selector:
    storm: supervisor
  template:
    metadata:
      labels:
        storm: supervisor
        app: storm
    spec:
      imagePullSecrets:
      - name: hub.cloudx5.com
      containers:
      - name: storm-supervisor
        image: hub.cloudx5.com/justep/storm:1.0.0
        imagePullPolicy: Always
        env:
        - name: ZOOKEEPER_SERVERS
          value: "10.96.100.11,10.96.100.12,10.96.100.13"
        - name: NIMBUS_SEEDS
          value: "10.96.100.31"
        - name: STORM_CMD
          value: "supervisor"
        volumeMounts:
        - name: storm-data
          mountPath: /usr/local/apache-storm/data
      volumes:
      - name: storm-data
        emptyDir: {}

